"""Compile the ViewDefinitions in fhir/view_definitions/ into dbt macros.

Each ViewDefinition <name>.json becomes dbt/macros/fhir_views/vd_<name>.sql, a
macro that takes the relation holding the FHIR resources (one JSON resource per
row, column `resource`). The same view can then run over any source:

    select * from {{ vd_patient_demographics(source('fhir', 'patient')) }}

Usage (from the repository root):
    python fhir/build_views.py            # (re)generate the macros
    python fhir/build_views.py --check    # exit 1 if a macro is out of date
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from sof_duckdb.compiler import compile_view  # noqa: E402

VIEWS_DIR = Path("fhir/view_definitions")
MACROS_DIR = Path("dbt/macros/fhir_views")
PLACEHOLDER = "__RELATION__"


def render(path: Path) -> str:
    view = json.loads(path.read_text())
    sql = compile_view(view, PLACEHOLDER)
    before, after = sql.split(PLACEHOLDER)
    return (
        f"{{# Generated by fhir/build_views.py from {path.as_posix()}. Do not edit. #}}\n"
        f"{{% macro vd_{view['name']}(relation) %}}\n"
        f"(\n{{% raw %}}{before}{{% endraw %}}{{{{ relation }}}}{{% raw %}}{after}{{% endraw %}}\n)\n"
        f"{{% endmacro %}}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if generated macros are out of date")
    args = ap.parse_args()

    MACROS_DIR.mkdir(parents=True, exist_ok=True)
    expected = {}
    for path in sorted(VIEWS_DIR.glob("*.json")):
        name = json.loads(path.read_text())["name"]
        expected[MACROS_DIR / f"vd_{name}.sql"] = render(path)

    stale = [p for p, text in expected.items() if not p.exists() or p.read_text() != text]
    orphans = [p for p in MACROS_DIR.glob("vd_*.sql") if p not in expected]
    if args.check:
        for p in stale + orphans:
            print(f"Out of date: {p}")
        sys.exit(1 if stale or orphans else 0)
    for p in orphans:
        p.unlink()
    for p, text in expected.items():
        p.write_text(text)
        print(f"{'updated' if p in stale else 'unchanged':9} {p}")


if __name__ == "__main__":
    main()
