# Synthea configuration overrides for this project
exporter.baseDirectory = ./data/synthea/
exporter.fhir.export = true
exporter.fhir.bulk_data = true
exporter.ccda.export = false
exporter.csv.export = false
exporter.hospital.fhir.export = false
exporter.practitioner.fhir.export = false
